"""add link in video class

Revision ID: 4767073e1ec5
Revises: a32ad5a2b54b
Create Date: 2017-11-16 15:12:17.682038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4767073e1ec5'
down_revision = 'a32ad5a2b54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'link')
    # ### end Alembic commands ###
