"""empty message

Revision ID: a200bd825ae1
Revises: 
Create Date: 2017-11-13 12:18:37.467868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a200bd825ae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exe_per_day', sa.String(length=10), nullable=True),
    sa.Column('exe_per_day_type', sa.String(length=10), nullable=True),
    sa.Column('rep', sa.String(length=10), nullable=True),
    sa.Column('exe_name', sa.String(length=10), nullable=True),
    sa.Column('exe_kcal', sa.String(length=10), nullable=True),
    sa.Column('exe_time', sa.String(length=10), nullable=True),
    sa.Column('exe_memo', sa.String(length=255), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_create_dttm'), 'diary', ['create_dttm'], unique=False)
    op.create_table('editableHTML',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editor_name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('editor_name')
    )
    op.create_table('etc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=True),
    sa.Column('fat', sa.String(length=10), nullable=True),
    sa.Column('skeletal_muscle', sa.String(length=10), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etc_create_dttm'), 'etc', ['create_dttm'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breakfast_food_type', sa.String(length=10), nullable=True),
    sa.Column('lunch_food_type', sa.String(length=10), nullable=True),
    sa.Column('dinner_food_type', sa.String(length=10), nullable=True),
    sa.Column('snack_food_type', sa.String(length=10), nullable=True),
    sa.Column('etc_food_type', sa.String(length=10), nullable=True),
    sa.Column('kcal_food', sa.String(length=10), nullable=True),
    sa.Column('food_name', sa.String(length=10), nullable=True),
    sa.Column('food_kcal', sa.String(length=10), nullable=True),
    sa.Column('food_memo', sa.String(length=255), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_create_dttm'), 'food', ['create_dttm'], unique=False)
    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_pressure_mmhg', sa.String(length=10), nullable=True),
    sa.Column('blood_suger_mddl', sa.String(length=10), nullable=True),
    sa.Column('mind_mg_dl', sa.String(length=10), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_create_dttm'), 'health', ['create_dttm'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('index', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_time', sa.String(length=10), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_create_dttm'), 'sleep', ['create_dttm'], unique=False)
    op.create_table('water',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_type', sa.String(length=10), nullable=True),
    sa.Column('water_type_name', sa.String(length=10), nullable=True),
    sa.Column('water_ml', sa.String(length=10), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_create_dttm'), 'water', ['create_dttm'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('diary_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('diary_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('water_id', sa.Integer(), nullable=True),
    sa.Column('sleep_id', sa.Integer(), nullable=True),
    sa.Column('health_id', sa.Integer(), nullable=True),
    sa.Column('etc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], ),
    sa.ForeignKeyConstraint(['etc_id'], ['etc.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['health_id'], ['health.id'], ),
    sa.ForeignKeyConstraint(['sleep_id'], ['sleep.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['water_id'], ['water.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_users')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_water_create_dttm'), table_name='water')
    op.drop_table('water')
    op.drop_index(op.f('ix_sleep_create_dttm'), table_name='sleep')
    op.drop_table('sleep')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_health_create_dttm'), table_name='health')
    op.drop_table('health')
    op.drop_index(op.f('ix_food_create_dttm'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_etc_create_dttm'), table_name='etc')
    op.drop_table('etc')
    op.drop_table('editableHTML')
    op.drop_index(op.f('ix_diary_create_dttm'), table_name='diary')
    op.drop_table('diary')
    # ### end Alembic commands ###
